default_settings: null
behaviors:
  CarDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.9
      gail:
        gamma: 0.99
        strength: 0.2
        encoding_size: 64
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: Demos/LeftTurnDemo.demo
    init_path: results/RightTurnImit5/CarDriver
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 400000
    time_horizon: 64
    summary_freq: 50000
    threaded: true
    self_play: null
    behavioral_cloning:
      demo_path: Demos/LeftTurnDemo.demo
      steps: 0
      strength: 0.2
      samples_per_update: 0
      num_epoch: null
      batch_size: null
    framework: pytorch
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: BothTurnImit
  initialize_from: RightTurnImit5
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
